// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FixieSpec")]
[assembly: AssemblyProductAttribute("FixieSpec")]
[assembly: AssemblyDescriptionAttribute("A super low friction specification test framework based on the fantastic Fixie test framework.")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-alpha1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
        internal const string InformationalVersion = "0.1.0-alpha1";
    }
}
