// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("FixieSpec")]
[assembly: AssemblyProductAttribute("FixieSpec")]
[assembly: AssemblyDescriptionAttribute("A super low friction specification test framework based on the fantastic Fixie test framework.")]
[assembly: AssemblyVersionAttribute("0.2.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0-alpha2")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FixieSpec";
        internal const System.String AssemblyProduct = "FixieSpec";
        internal const System.String AssemblyDescription = "A super low friction specification test framework based on the fantastic Fixie test framework.";
        internal const System.String AssemblyVersion = "0.2.0";
        internal const System.String AssemblyFileVersion = "0.2.0";
        internal const System.String AssemblyInformationalVersion = "0.2.0-alpha2";
        internal const System.Boolean ComVisible = false;
    }
}
